// Turns drizzle-kit's SQL migrations into a typed TypeScript module, so the app needs no Babel
// or Metro changes to load .sql files and no untyped imports reach our code.
import { MigrationJournal, migrationKey } from "../src/migration-bundle";

const root = new URL("..", import.meta.url);
const journal = MigrationJournal.parse(await Bun.file(new URL("drizzle/meta/_journal.json", root)).json());

const migrations: Record<string, string> = {};
for (const entry of journal.entries) {
  migrations[migrationKey(entry.idx)] = await Bun.file(new URL(`drizzle/${entry.tag}.sql`, root)).text();
}

const source = `// Generated by scripts/bundle-migrations.ts from drizzle/. Do not edit; run \`bun run db:generate\`.
import type { MigrationBundle } from "./migration-bundle";

export const migrationBundle: MigrationBundle = ${JSON.stringify({ journal, migrations }, null, 2)};
`;

await Bun.write(new URL("src/migrations.generated.ts", root), source);
console.log(`Bundled ${String(journal.entries.length)} migration(s) into src/migrations.generated.ts`);
